### ISSUE TITLE
nrgsrc.com is down

### ISSUE THREAD

**Issue by kenorb** [genesisdotre/ngrsrc#1]
URL: https://genesisdotre.github.io/ngrsrc

**Comment by stefek99** [comment]
https://who.is/whois/nrgsrc.com

> Registrar Registration Expiration Date: 2017-01-24T01:47:00.00Z

Domain wasn't extended...

Where do you find the dead link?

**Comment by kenorb** [comment]
You can then fallback to the github.io domain, without the redirect. I don't know where I've found it, probably by accident:)
